### PR TITLE
OrgLeader limitations fixes

### PR DESCRIPTION
**Pull request by ExistentialEnso**
This addresses #8 and #9 on Kayan's list.

For #8, it adds a setting that makes it so that OrgLeadersOnly users can only access the /Org/ page for the orgs in which they are a Leader. For ones in which they are just a member, they get the /OrgContent/ link instead on the Current tab and no link at all on the other two tabs.

For #9, it adds a setting that makes it so that OrgLeadersOnly users only get the pared down, basic blue toolbar that MyData users traditionally get.

### CODE REVIEW

**Comment by ExistentialEnso** [comment]
It looks like we will need something a bit different for #9 based on your post-meeting email.

**Comment by ExistentialEnso** [comment]
Updated the toolbar to work per your notes after the meeting today.

**Comment by drmohundro** [comment]
See https://clearfunction.sifterapp.com/issues/150

**Comment by drmohundro** [comment]
See https://clearfunction.sifterapp.com/issues/151

**Pull request merged**
