### PR TITLE
Involvement tab tweaks

### PR DESCRIPTION
**Pull request by ExistentialEnso**
Resolves #1 and #2 on Kayan's list.

There doesn't seem to be anything on OrgType that would enable us to intelligently decide what should be in the filter. So I have it implemented as a setting currently that lets you exclude types.

### CODE REVIEW

**Comment by ExistentialEnso** [comment]
It just dawned on me that we could also get the list of types by selecting them out of the person's list of orgs.

This would also come with the added benefit of not showing types that don't apply to the user.

I'm happy to implement that if you think that's the right route. We could still keep the exclusion list if there is any benefit to be had there, though I guess that wouldn't be Redeemer's use case. Maybe other TouchPoint users?

**Comment by drmohundro** [comment]
I like the idea of filtering off of the user's displayed list of orgs (assuming we still handle parent/child orgs, too). Let's try that approach.

**Comment by ExistentialEnso** [comment]
The list is now only populated with values actually in the list.

I went ahead and kept the exclusion setting functionality since Kayan mentioned "Staff Use Only" should not ever display in there, and one of the users I tested had a membership in a few of these groups.

**Comment by drmohundro** [comment]
For records - this tracks https://clearfunction.sifterapp.com/issues/146 and https://clearfunction.sifterapp.com/issues/147.

**Pull request merged**
